name: Merge branch Action
on:
  pull_request:
    branches:
      - bugs
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: quangvo09/pull-request-action@v1
        name: Create PR to features
        with:
          github_token: ${{ secrets.TOKEN }}
          branch_prefix: bugs
          base_branch: features
