name: Merge branch Action
on:
  pull_request:
    branches:
      - bugs
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: features
      - name: Reset features branch
        run: |
          git fetch origin bugs:bugs
          gir reset --hard bugs
      - uses: peter-evans/create-pull-request@v3
        name: Create PR to features
        with:
          branch: bugs-promotion
