name: Merge branch Action
on:
  schedule:
    - cron:  '19 * * * *'
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: features
      - name: Reset features branch
        run: |
          git fetch origin bugs:bugs
          git reset --hard bugs
      - uses: peter-evans/create-pull-request@v3
        name: Create PR to features
        with:
          branch: bugs
          commit-message: Merge bugs to features
          title: Merge bugs to features
          body: Automated PR to merge bugs to features
