name: Merge branch Action
on:
  pull_request:
    branches:
      - bugs
jobs:
  Create-Pull-Request-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v3
        name: Create PR to features
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR
          title: 'Auto PR'
          branch: bugs

          
